// Data shape: 
// [{ timestamp(str), category(str), store(str), cost(2-decimal float) }]

const categories = ['Fast Food', 'Restaurants & Bars', 'Groceries', 'Clothes', 'Health & Beauty', 'Home', 'Bills', 'Misc.'];
const stores = ["A & W","AERIE","ALDO / ALDO ACCESSORIES","AMERICAN EAGLE OUTFITTERS","APPLE","ARBY'S","ARITZIA","AROMA ESPRESSO BAR","ATMOSPHERE","BANANA REPUBLIC","BATH & BODY WORKS","BELL","BENTLEY","BEST BUY MOBILE","BIG LEAGUES","BIG ORANGE","BIKINI VILLAGE","BIZOU","BLACKWELL SUPPLY CO.","BLUENOTES","BOATHOUSE","BONLOOK","BOURBON STREET GRILL","BROWNS","BUILD-A-BEAR WORKSHOP","CALENDAR CLUB","CALL IT SPRING","CARYL BAKER VISAGE","CELLICON","CF ADMINISTRATION OFFICE","CF MASONVILLE PLACE - GUEST SERVICES","CHAMPS","CHARM DIAMOND CENTRES","CHATR MOBILE","CHATTERS","C.I.B.C. BANK (NE PARKING LOT)","CINNABON","CLAIRE'S ACCESSORIES","CLEO","COLES","CONTINENTAL CURRENCY EXCHANGE","DAIRY QUEEN / ORANGE JULIUS","DANIER","DAVIDSTEA","DENTAL OFFICE: TOOTHWORKS","DISNEY STORE","DYNAMITE","EB GAMES","FAST TIME WATCH & JEWELLERY REPAIR","FIDO","FLIGHT CENTRE","FONELAB","FOOT LOCKER","FOREVER 21","FOSSIL","FREEDOM MOBILE","FRESHII","FRESHLY SQUEEZED","GAP / GAP KIDS","GARAGE","GENTLEMEN'S BARBER, THE","GIFT WRAP VALET","GNC - GENERAL NUTRITION CENTRE","GREEN EARTH","GUESS","GYMBOREE","H & M","HAIR EFFECTS","HALLMARK","HEARING SOLUTIONS","HOT TOPIC","HUDSON'S BAY","INS","JACK & JONES","JEAN MACHINE","JIMMY THE GREEK","JOURNEYS","JUST COZY","KERNELS","KFC / TACO BELL","KIEHL'S","KOODO","KOYA JAPAN","LA SENZA","LA VIE EN ROSE","LALINE","LAURA","LAURA SECORD","LE CHATEAU","LENSCRAFTERS","LIDS","LINDT CHOCOLATE","LITTLE BURGUNDY","L'OCCITANE EN PROVENCE","LONDON SHOE RENEW","LULULEMON ATHLETICA","LUSH FRESH HANDMADE COSMETICS","M BOUTIQUE-(COMING SOON)","MAC","MAC'S SUSHI","MANCHU WOK","MAPPINS","MARSHALLS / HOMESENSE","MELANIE LYNE","MICHAEL HILL JEWELLER","MICHAEL KORS","MILESTONES","MINISO","MOBILINQ","MR. SUB","NANDO'S PERI PERI CHICKEN","NEW YORK FRIES","NRSH","NUTRITION HOUSE","NYX PROFESSIONAL MAKEUP","OLSEN EUROPE","OROGOLD COSMETICS","PANDORA","PAYLESS SHOESOURCE","PEOPLES JEWELLERS","QE HOME","REAL FRUIT BUBBLE TEA (COMING SOON)","ROCKY MOUNTAIN CHOCOLATE FACTORY","ROGERS","ROOTS","ROYAL BEE","RW & CO.","SAJE NATURAL WELLNESS","SANTA","SANTA VILLE","SCOTIABANK","SEPHORA","SHOPPERS DRUG MART","SHOWCASE","SILVERCITY","SKECHERS","SOFTMOC","SPENCER GIFTS","SPORT CHEK / ATMOSPHERE","STARBUCKS","STITCH IT","SUNGLASS HUT","SUNRISE RECORDS","SWAROVSKI","SWIMCO","TANGERINE BANK","TBOOTH WIRELESS","TELUS MOBILITY","THAI EXPRESS","THE BODY SHOP","THE CUT ABOVE","THE FACE SHOP","THE KEG STEAKHOUSE & BAR","THE REC ROOM","THE SOURCE","THINGS ENGRAVED","TIM HORTONS","TIP TOP TAILORS","TORRID","TOWN SHOES","TRADE SECRETS","TRANSAT TRAVEL","URBAN PLANET","VICTORIA'S SECRET / PINK","VIRGIN MOBILE","VOGUE OPTICAL","WALKING ON A CLOUD","WATCH IT!","WIRELESSWAVE","WOW! MOBILE BOUTIQUE","ZACK'S","ZARA","ZUMIEZ"];

function randomDate(start, end, startHour, endHour) {
  var date = new Date(+start + Math.random() * (end - start));
  var hour = startHour + Math.random() * (endHour - startHour) | 0;
  date.setHours(hour);
  return date;
}

var date1 = new Date('December 17, 1995 03:24:00');

for (let i = 0; i < 100; i++) {
  categories[Math.floor(Math.random()*categories.length)]
  stores[Math.floor(Math.random()*stores.length)]
  console.log( (Math.random() * 20).toFixed(2) );
  console.log(randomDate(new Date('September 1, 2018 00:00:00'), new Date('December 1, 2018 00:00:00'), 0, 23));
}